export RIGIDITY_LAMBDA=0.1
export LAMBDA_SPRING=0.0
export LAMBDA_ISOMETRIC=0.3

python3 train.py -s data/final_scenes/scene_1/ --port 6021 --expname "final_scenes/scene_1" --configs arguments/mdnerf-dataset/cube.py --lambda_w 100000 --lambda_rigidity $RIGIDITY_LAMBDA --lambda_spring $LAMBDA_SPRING --lambda_momentum 0.1 --use_wandb --wandb_project final_scene_1 --wandb_name init --k_nearest 5 --lambda_isometric $LAMBDA_ISOMETRIC
python3 train.py -s data/final_scenes/scene_2/ --port 6022 --expname "final_scenes/scene_2" --configs arguments/mdnerf-dataset/cube.py --lambda_w 100000 --lambda_rigidity $RIGIDITY_LAMBDA --lambda_spring $LAMBDA_SPRING --lambda_momentum 0.1 --use_wandb --wandb_project final_scene_2 --wandb_name init --k_nearest 5 --lambda_isometric $LAMBDA_ISOMETRIC
python3 train.py -s data/final_scenes/scene_3/ --port 6023 --expname "final_scenes/scene_3" --configs arguments/mdnerf-dataset/cube.py --lambda_w 100000 --lambda_rigidity $RIGIDITY_LAMBDA --lambda_spring $LAMBDA_SPRING  --lambda_momentum 0.1 --use_wandb --wandb_project final_scene_3 --wandb_name init --k_nearest 5 --lambda_isometric $LAMBDA_ISOMETRIC
python3 train.py -s data/final_scenes/scene_4/ --port 6024 --expname "final_scenes/scene_4" --configs arguments/mdnerf-dataset/cube.py --lambda_w 100000 --lambda_rigidity $RIGIDITY_LAMBDA --lambda_spring $LAMBDA_SPRING  --lambda_momentum 0.1 --use_wandb --wandb_project final_scene_4 --wandb_name init --k_nearest 5 --lambda_isometric $LAMBDA_ISOMETRIC
python3 train.py -s data/final_scenes/scene_5/ --port 6025 --expname "final_scenes/scene_5" --configs arguments/mdnerf-dataset/cube.py --lambda_w 100000 --lambda_rigidity $RIGIDITY_LAMBDA --lambda_spring $LAMBDA_SPRING  --lambda_momentum 0.1 --use_wandb --wandb_project final_scene_5 --wandb_name init --k_nearest 5 --lambda_isometric $LAMBDA_ISOMETRIC
python3 train.py -s data/final_scenes/scene_6/ --port 6026 --expname "final_scenes/scene_6" --configs arguments/mdnerf-dataset/cube.py --lambda_w 100000 --lambda_rigidity $RIGIDITY_LAMBDA --lambda_spring $LAMBDA_SPRING  --lambda_momentum 0.1 --use_wandb --wandb_project final_scene_6 --wandb_name init --k_nearest 5 --lambda_isometric $LAMBDA_ISOMETRIC
